<footer>
  <div class="inner cf">
    <div class="sns_btn_area cf">
      <p class="fb">
        <a class="facebook" href="javascript:void(0);" onclick="window.open('http://www.facebook.com/share.php?u=http://ooo.jp' ,null ,'width=650 ,height=450'); return false;" rel="nofollow"><span class="sns_btn">fb</span></a><!-- ooo.jpは入れたいアドレス -->
      </p>
      <p class="tw">
        <a href="javascript:void(0)" onClick="d=document,e=encodeURIComponent,t=(d.selection)?d.selection.createRange().text:(window.getSelection)?window.getSelection():(d.getSelection)?d.getSelection():'',f='http://twitter.com/share?url=URL&text='+e(document.title)+' '+e(location.href)+'&url=';if(!window.open(f,'','width=500,height=500'))location.href=f;void(0);return false"><span class="sns_btn">tw</span></a>
      </p>
      <p class="gp">
        <a href="https://plus.google.com/share?url=http://ooo.jp" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><span class="sns_btn">g<sup>+</sup></span></a><!-- ooo.jpは入れたいアドレス -->
      </p>
    </div>
    <!-- /.sns_btn -->

    <div class="footer_link_area">
      <ul>
        <li><a href="/template/base01/privacy/">プライバシーポリシー</a></li>
        <li><a href="/template/base01/sitemap/">サイトマップ</a></li>
      </ul>
    </div>
  </div>
  <p class="copyright">Copyright <span class="copy">&copy;</span> コーディングテンプレ All Rights Reserved.</p>
</footer>
