<div class="layer"></div>
<header>
  <div id="header" class="cf">
    <div class="inner">
      <p id="siteLogo"><a href="/template/base01/">Logo</a></p>
      <p class="catch">キャッチコピー</p>
      <div class="sp_obj nav">
        <!-- SP版ナビ -->
        <div class="navOpen">
          <span class="top"></span>
          <span class="middle"></span>
          <span class="bottom"></span>
        </div>
        <nav>
          <ul class="navInner">
            <li class="op"><a href="/template/base01/about/"><span>会社概要</span></a>
            </li>
            <li class="op"><a href="/template/base01/news/"><span>ニュース</span></a>
            </li>
            <li class="op"><a href="/template/base01/products/"><span>製品情報</span></a>
            </li>
            <li class="op"><a href="/template/base01/shop/"><span>店舗一覧</span></a>
            </li>
            <li class="op"><a href="/template/base01/faq/"><span>お問い合わせ</span></a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>
