<!-- インクルードはルートパスで！ -->
<div id="nav" class="pc_obj">
  <nav>
    <ul class="navInner">
      <li class="op"><a href="/template/base01/about/"><span>会社概要</span></a>
        <ul>
          <li><a href="/template/base01/about/president.html"><span>社長あいさつ</span></a></li>
        </ul>
      </li>
      <li class="op"><a href="/template/base01/news/"><span>ニュース</span></a>
        <ul>
          <li><a href="/template/base01/news/detail/01.html"><span>詳細</span></a></li>
        </ul>
      </li>
      <li class="op"><a href="/template/base01/products/"><span>製品情報</span></a>
        <ul>
          <li><a href="/template/base01/products/detail/"><span>詳細</span></a></li>
        </ul>
      </li>
      <li class="op"><a href="/template/base01/shop/"><span>店舗一覧</span></a>
      </li>
      <li class="op"><a href="/template/base01/"><span>お問い合わせ</span></a>
        <ul>
          <li><a href="/template/base01/faq/"><span>よくある質問</span></a></li>
          <li><a href="/template/base01/form/"><span>フォーム</span></a></li>
          <li><a href="/template/base01/form/confirm.html"><span>確認</span></a></li>
          <li><a href="/template/base01/form/complete.html"><span>完了</span></a></li>
        </ul>
      </li>
    </ul>
  </nav>
</div>
